[build]
  publish = ".next"
  command = "npm ci --legacy-peer-deps && npm run build"

[build.environment]
  # Aggiorna Node.js alla versione 20 per TypeScript
  NODE_VERSION = "20"
  # Variabili d'ambiente per il build
  NODE_ENV = "production"

# Configurazione funzioni Netlify
[functions]
  directory = "netlify/functions"