// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  footer: dynamic(() => import("./Footer")),
  rich_text: dynamic(() => import("./BaseText")),
};
